- name: Create the ELB only listening over port 80
  ec2_elb_lb:
    name: "{{ ELBNAME }}"
    state: present
    region: us-east-2
    zones:
      - us-east-2b
      - us-east-2c
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
  register: "{{ ELBNAME }}"

- name: Create EC2 instances
  ec2:
    key_name: krm-ohio
    instance_type: t2.nano
    image: ami-0986c2ac728528ac2
    user_data: "{{ USERDATA }}"
    region: us-east-2
    group_id:
      - sg-07b74d48769152418 
    wait: yes
    instance_tags:
      Name: web_server
      application: "{{ application }}"
    exact_count: 2
    count_tag:
      application: "{{ application }}"
  register: ec2_instances

- name: Wait for servers to come online
  wait_for:
    host: "{{ item.public_ip }}"
    port: 80
    timeout: 350
  with_items: "{{ ec2_instances.tagged_instances }}"
  ignore_errors: True

- name: Add each EC2 instance to the ELB
  ec2_elb:
    state: present
    ec2_elbs: "{{ ELBNAME }}"
    region: us-east-2
    instance_id: "{{ item.id }}"
  with_items: "{{ ec2_instances.tagged_instances }}"
